### PR TITLE
Fix isValid() to invalidate short codes with padding (issues/273)

### PR DESCRIPTION
**Pull request by JonMcPherson**
This PR updates all implementations with an additional check to `isValid(string)` to invalidate short codes with padding as discussed in Issue https://github.com/google/open-location-code/issues/273.
The Open Location Code Specification doc was also updated to clarify that padded codes cannot be shortened and that short codes cannot have padding.
The invalid padded short code `WC2300+` was also added to ` test_data/validityTests.csv` as an invalid test case.

The additional check is consistent between each contained implementation as much as possible and is structured like:
```
if (code contains padding) {
    // Short codes cannot have padding
    if (separatorIndex < SEPARATOR_POSITION) {
        return false;
    }
    ...
}
```

### CODE REVIEW

**Comment by JonMcPherson** [comment]
The build failed due to a connection timeout error and I cannot trigger a rebuild without pushing some change.
All tests have passed.

**Comment by drinckes** [comment]
Hi @JonMcPherson - I moved the spec into a separate file. It explicitly says padded codes can't be shortened, so I think that should be ok?

**Comment by drinckes** [comment]
Resolved merge conflict caused by me migrating the spec out of the definition.

**Comment by drinckes** [comment]
Thanks @JonMcPherson !

**Comment by JonMcPherson** [comment]
cool! glad I could help. :thumbsup:

**Comment by 1Alibin2Ali** [comment]
7H6773G7ال قير, اليمن

**Pull request merged**
