### PR TITLE
Add Maven configuration for Java library.

### PR DESCRIPTION
**Pull request by zongweil**

### CODE REVIEW

**Comment by zongweil** [comment]
This is for #165

**Comment by zongweil** [comment]
Looks like the Bazel build in Travis CI is breaking. I'll update the PR and let you know when it's fixed.

**Comment by drinckes** [comment]
OK, np.

**Comment by drinckes** [comment]
Tests still failing. Could it be because you changed the path to read the test files?

**Comment by zongweil** [comment]
Yes, I need to figure out how to have the tests pass via both Bazel and Maven. I was having trouble running Bazel v0.13.1 on my corp desktop. I installed an older version on my personal desktop last night and I'll work on that soon.

**Comment by zongweil** [comment]
My git client got messed up after trying to merge some changes. I'll send a new PR.

**Pull request closed without merging**
