### PR TITLE
Python implementation

### PR DESCRIPTION
**Pull request by Stevemasha**
Please consider this python implementation

### CODE REVIEW

**Comment by drinckes** [comment]
Hi Steve. Could you write it as a python class, rather than a simple file? Also  bear in mind is that I'll ask you to write another python script that uses that class and runs the tests, to make sure that there are no problems in the code.

**Comment by Stevemasha** [comment]
Hi Doug,I have converted the file to python class and wrote another scripts that runs the tests.

**Comment by drinckes** [comment]
You've converted the code into a class but your class has no state - it's just a container for the methods.

The class initialiser can provide the functionality of encode(), decode(), and recover_nearest() as follows:

    class OpenLocationCode(object):
      def __init__(self, latitude=None, longitude=None, code_length=None,
                   full_olc_code=None, partial_olc_code=None):

Check for valid combinations (below), making sure to throw an exception if you get too many/not enough/the wrong combination of arguments:
1. Initialised with lat and lng, that's basically encode() with the default length
2. Initialised with lat, lng and length are encode() with the specified length
3. Initialised with full_olc_code - needs to decode()
4. Initialised with a short code, lat and lng is recover_nearest()

For bonus points, you could define/throw different exceptions:
  * ArgumentError if the combination of arguments isn't any of the above
  * BadCodeError if the full or partial code isn't valid

Then, you would call it like:

    a = OpenLocationCode(latitude=lat, longitude=lng)
    b = OpenLocationCode(latitude=lat, longitude=lng, length=13)
    c = OpenLocationCode(full_olc_code='8FVC9G8F+7X')
    d = OpenLocationCode(parial_olc_code='8F+7X', latitude=lat, longitude=lng)

You should store the code and the coordinates in the class (as private attributes) and have methods to access them, say:

    def getCode(self):
      """Returns the current full code."""

    def getCodeLength(self):
      """Returns the length of the current code."""

    def getCoordinates(self):
      """Returns the coordinates of the code area.

      Returns a list with [lat_sw, lng_sw, lat_ne, lng_ne].
      """

This way, you pretty much don't need any other methods to be public - not even isFull or isValid, because you can just try to create an object with it and catch the exception. Because of that, it'd be good to have a separation between the public and private methods, so could you add a "_" in front of all methods that aren't getCode, getCodeLength and getCoordinates? (If you want to expose isFull, isValid and isShort that's fine too. But the others, like decode() etc, don't need to be visible.)

Finally, and I know this is quite big already, but can you use the test data files in the test_data directory? Then if we ever need to add tests, we don't need to modify all the implementations.

Thanks,
Doug

**Comment by drinckes** [comment]
I'm closing this request since there's been no response for so long.

**Pull request closed without merging**
