### PR TITLE
Add initial dart support. Mostly mimics current js implementation.

### PR DESCRIPTION
**Pull request by mdakin**
Please add initial dart implementation.

### CODE REVIEW

**Comment by mdakin** [comment]
Friendly ping :)

**Comment by drinckes** [comment]
Your test files are copies of the existing ones. Could you just use those rather than replicating them?

Note that a new test case has been added that will probably require you to modify your isValid method. See the JS, I just modified it.

Could you add to the readme how the code can be tested?

Thanks

**Comment by mdakin** [comment]
Thanks, Fixed the issue, also now uses test_data from project root directory and added directions to readme run the tests. please take a look.

**Comment by drinckes** [comment]
OK, great! I'm happy with the code. Before I can merge it into the project I need you to sign the [Google Individual Contributor License Agreement](https://developers.google.com/open-source/cla/individual?csw=1) . See the CONTRIBUTING.md file.  Let me know and if I haven't gone on vacation I'll merge your files straight away.

Thanks!

**Comment by mdakin** [comment]
Hi Doug,

Thanks, I have the agreement signed some time ago, also AFAIK, Google
Employees are not required to sign it (At least it was the case when I
contributed to Dart project).

Anyway, I think we are good.

Thanks
Mehmet

**Comment by drinckes** [comment]
Thanks! Sorry for the delay.

**Pull request merged**
