### PR TITLE
Fix floating point tests in Rust implementation 

### PR DESCRIPTION
**Pull request by drinckes**
Fix final floating point tests in rust implementation by using integer operations for encode and decode.

### CODE REVIEW

**Comment by drinckes** [comment]
Impact:
* encoding is slower (~1usec to ~3usec)
* decoding is faster (~25usec to ~14usec)

**Comment by drinckes** [comment]
Hi Sergey

There was one failing test - I ended up changing the implementation in this library to the integer based solution that e.g. the Java library uses, and just translated it to rust.

Given that I don't really know rust at all, could you take a look and see if there's anything terrible I've done?

**Comment by drinckes** [comment]
Thanks - merging then!

**Comment by Ralfhin** [comment]
P237+J8

**Pull request merged**
