### PR TITLE
Fix some of the problems issued by @dgryski

### PR DESCRIPTION
**Pull request by tgulacsi**
I've seen only the issues, and not his PRs...

These changes incorporates PR #14 and PR #19, hopefully solves Issue #16 and Issue #17.

### CODE REVIEW

**Comment by dgryski** [comment]
Closed my PRs included in this one.

**Comment by drinckes** [comment]
What is the purpose of the go/corpus/xx files? If they're only generated for testing from the files in test_data, do they need to be checked in?

**Comment by tgulacsi** [comment]
Right, they're generated.
2015. aug. 19. 13:25 ezt írta ("Doug Rinckes" <notifications@github.com>):

**Comment by drinckes** [comment]
I forget if I've asked you for this elsewhere (I thought I had yesterday but I can't find it in the comments or the issues) - could you add a README.md file with how to run the tests? 

I'm trying to add automated test running with travis-ci but my go isn't good enough to figure out what all the files are for. :-)

**Comment by dgryski** [comment]
The files are only using when running go-fuzz; they're not needed as part of the standard test suite, and you wouldn't run go-fuzz as part of an integration test.  However, since running go-fuzz burns CPU, it's nice to have an already generated corpus ready for use so people can pick up from where @tgulacsi left off.

**Pull request merged**
