### PR TITLE
Pluscode implementation for plpgsql (PostgreSQL)

### PR DESCRIPTION
**Pull request by benno-p**
Classic functions : 
pluscode_isvalid()
pluscode_isshort()
pluscode_encode()
pluscode_decode()
pluscode_shorten()
pluscode_codearea()
pluscode_cliplatitude()
pluscode_normalizelongitude()

### CODE REVIEW

**Comment by benno-p** [comment]
@googlebot I signed it!

**Comment by bilst** [comment]
Thanks for contributing! Would it be possible to add tests so that we can guard against future bugs/breakages? Some pointers:
https://github.com/google/open-location-code/blob/master/CONTRIBUTING.md
https://github.com/google/open-location-code/blob/master/TESTING.md

**Comment by benno-p** [comment]
Thanks for the return,

 

I added files for testing the pluscode functions.

I'm not comfortable with bazel…

 

Is it okay for you ?

 

Benoit Perceval

 

De : bilst [mailto:notifications@github.com] 
Envoyé : mardi 24 novembre 2020 00:11
À : google/open-location-code <open-location-code@noreply.github.com>
Cc : Benno <b.perceval@superceval.fr>; Author <author@noreply.github.com>
Objet : Re: [google/open-location-code] Pluscode implementation for plpgsql (PostgreSQL) (#419)

 

Thanks for contributing! Would it be possible to add tests so that we can guard against future bugs/breakages? Some pointers:
https://github.com/google/open-location-code/blob/master/CONTRIBUTING.md
https://github.com/google/open-location-code/blob/master/TESTING.md

**Review by bilst — APPROVED** [review]
Thanks!

**Pull request merged**
