### PR TITLE
Implement max code length behavior for Python

### PR DESCRIPTION
**Pull request by WilliamDenniss**
Implements #190 for Python.

### CODE REVIEW

**Comment by drinckes** [comment]
Thanks William - I'd like to avoid having tests coded in implementations so that we have a common set of tests.

I realise that the current test files don't allow this, so I'm going to split the encoding and decoding tests into two files. (Issue #288, PR for the split and JS in #289.)

Once #289 is done, could you add your tests to that file, and then update the python tests to read from the new files?

I note that the JS test failed and I'll look into that.

**Comment by WilliamDenniss** [comment]
Good plan! That's a much better approach.

I'll update this PR today to match, and can implement the split-test feature for Python as well.

**Comment by drinckes** [comment]
I fixed the JS test (and a few others besides that had errors but weren't causing the builds to fail - it was just silently ignoring the errors).

**Comment by drinckes** [comment]
That button doesn't say cancel, does it? :-)

**Comment by zongweil** [comment]
Doug, I was waiting for all implementations to make the max length changes before adding common test cases to the CSV (otherwise tests would fail). I took a look through the implementations and at this point, all the implementations referencing the CSV are actually updated, so we can finally consolidate.

**Comment by WilliamDenniss** [comment]
Replaced by #300.

@zongweil good to know, will be looking to see if they all pass the tests I just added.

**Pull request closed without merging**
