### PR TITLE
Add test case for floating point bug

### PR DESCRIPTION
**Pull request by drinckes**
Add test case to illustrate #307 .

### CODE REVIEW

**Comment by drinckes** [comment]
@zongweil I was going to merge this into master, then fix the implementations one by one. That means the build thing will indicate broken until they're all done. What do you think?

**Comment by zongweil** [comment]
I ran into a similar situation when implementing the max length for all the implementations. I went with adding individual test cases in all the implementations until they were all done, but it was definitely a non-trivial amount of work added up. 

What if we left the test case commented out? We could easily uncomment it when running tests locally/on Travis CI to verify the fix for a particular implementation.

**Comment by drinckes** [comment]
I normally don't like putting in changes that break stuff, but since it's confirming what's working and what isn't, and we have a plan to update the implementations, I think it's ok?

**Comment by zongweil** [comment]
As discussed over chat, let's submit these for now. Can you update the 1.2, 3.4 test case as well? The "precise" code should be 6FH559XX+XX.

**Comment by zongweil** [comment]
I'll start posting issues in the external implementations after these test cases are submitted.

**Comment by WilliamDenniss** [comment]
One approach for this kind of update that I've used in the past are branches. You can have the dev branch failing CI as each of the implementations get fixed, then merge to master once it's all implemented.  This is particularly useful if we also want to continue to accept contributions to HEAD while that work is ongoing, as those changes can be tested separately. It's also a good way to track feature completion.

**Pull request merged**
