### PR TITLE
Replace fabs call in C++ implementation.

### PR DESCRIPTION
**Pull request by zongweil**
Slight performance improvement by negating a value that is known to be
negative instead of calling fabs().

Copied from #150.

### CODE REVIEW

**Comment by zongweil** [comment]
Hey Doug, I think we need to use the latest version of Bazel in Travis-CI. Is that an easy configuration option?

**Comment by drinckes** [comment]
The Bazel version is downloaded and defined in .travel.yml. Currently it's on 0.5.3 so yeah it probably needs updating. I'm trying to update the Baze and closure rules versions in #173 but I'm having trouble getting it green.

**Comment by drinckes** [comment]
I think you can try syncing this branch and picking up the #173 changes - the build should work (hopefully!).

**Comment by zongweil** [comment]
Thanks, it works now!

**Pull request merged**
