### PR TITLE
Add max length for Rust library.

### PR DESCRIPTION
**Pull request by zongweil**
#190

### CODE REVIEW

**Comment by zongweil** [comment]
@drinckes PTAL, first time writing Rust so let me know if there's a more idiomatic way to do this :).

**Comment by drinckes** [comment]
Yeah, this is about the total of my Rust experience as well. I'm going to say LGTM but if anyone else would like to take a look that would be great.

(Maybe give it a couple of days to give anyone a chance, then merge.)

**Comment by sallybelly** [comment]
Leave me alone I've been the target, it's time to move on.

**Comment by sallybelly** [comment]
I'm protected by the precious blood of the lamb, Jesus Christ my Lord and saviour. In jesys name I command you all to stop right now. Quit trying to locate me, leave me alobe.

**Pull request merged**
